services:
  n3fjp-map:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: n3fjp-map
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config:ro
      - ./app/static:/app/static
    env_file:
      - .env
    environment:
      - CONFIG_FILE=/config/config.yaml
